# Generated by Django 5.2.7 on 2025-10-20 19:53

import django.core.validators
import django.db.models.deletion
import projects_tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='projects_tool.board')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g., #AABBCC).', regex='^#([A-Fa-f0-9]{6})$')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects_tool.project')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='projects_tool.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('priority', models.CharField(choices=[('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], default='ME', max_length=2)),
                ('story_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), projects_tool.models.validate_divisible_by_5])),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='projects_tool.label')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects_tool.list')),
            ],
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('board', 'title'), name='unique_list_title_per_board'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_label_title_per_project'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_board_title_per_project'),
        ),
    ]
